\echo 'flood_map_with_depth_drained_surface_water_1in1000_present_day - Renaming _valid table original table'

ALTER TABLE fmp.flood_map_with_depth_drained_surface_water_1in1000_valid RENAME TO flood_map_with_depth_drained_surface_water_1in1000_present_day;
